<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CooperativeSeeder extends Seeder
{
    public function run()
    {
        DB::table('cooperatives')->insert([
            [
                'name' => 'Sunrise Farmers Coop',
                'contact_person' => 'Juan Dela Cruz',
                'type' => 'Agricultural',
                'address' => '123 Farm Road, Laguna',
                'region' => 'Region IV-A',
                'phone_number' => '09123456789',
                'email' => 'sunrisefarmers@example.com',
                'tin' => '123-456-789',
                'coop_identification_no' => 'COOP-0001',
                'bod_chairperson' => 'Pedro Santos',
                'general_manager_ceo' => 'Maria Lopez',
                'ga_registration_status' => 'Registered',
                'total_asset' => 500000.00,
                'total_income' => 150000.00,
                'cetf_remittance' => 20000.00,
                'cetf_required' => 25000.00,
                'cetf_balance' => 5000.00,
                'share_capital_balance' => 300000.00,
                'no_of_entitled_votes' => 50,
                'services_availed' => 'Microfinance, Training Programs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Metro Transport Coop',
                'contact_person' => 'Luis Mendoza',
                'type' => 'Transport',
                'address' => '456 Main Street, Manila',
                'region' => 'NCR',
                'phone_number' => '09234567890',
                'email' => 'metrotransport@example.com',
                'tin' => '234-567-890',
                'coop_identification_no' => 'COOP-0002',
                'bod_chairperson' => 'Ricardo Gomez',
                'general_manager_ceo' => 'Angela Reyes',
                'ga_registration_status' => 'Registered',
                'total_asset' => 800000.00,
                'total_income' => 300000.00,
                'cetf_remittance' => 35000.00,
                'cetf_required' => 40000.00,
                'cetf_balance' => 5000.00,
                'share_capital_balance' => 450000.00,
                'no_of_entitled_votes' => 75,
                'services_availed' => 'Vehicle Loans, Insurance',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Green Energy Coop',
                'contact_person' => 'Carmen Santiago',
                'type' => 'Energy',
                'address' => '789 Solar Avenue, Cebu City',
                'region' => 'Region VII',
                'phone_number' => '09345678901',
                'email' => 'greenenergy@example.com',
                'tin' => '345-678-901',
                'coop_identification_no' => 'COOP-0003',
                'bod_chairperson' => 'Carlos Dela Rosa',
                'general_manager_ceo' => 'Isabel Martinez',
                'ga_registration_status' => 'Registered',
                'total_asset' => 1200000.00,
                'total_income' => 450000.00,
                'cetf_remittance' => 50000.00,
                'cetf_required' => 55000.00,
                'cetf_balance' => 5000.00,
                'share_capital_balance' => 700000.00,
                'no_of_entitled_votes' => 100,
                'services_availed' => 'Renewable Energy, Consulting',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Seaside Fisherfolk Coop',
                'contact_person' => 'Manuel Rodriguez',
                'type' => 'Fisheries',
                'address' => '123 Coastal Road, Davao',
                'region' => 'Region XI',
                'phone_number' => '09456789012',
                'email' => 'seasidefisheries@example.com',
                'tin' => '456-789-012',
                'coop_identification_no' => 'COOP-0004',
                'bod_chairperson' => 'Jorge Lim',
                'general_manager_ceo' => 'Theresa Uy',
                'ga_registration_status' => 'Registered',
                'total_asset' => 650000.00,
                'total_income' => 200000.00,
                'cetf_remittance' => 25000.00,
                'cetf_required' => 30000.00,
                'cetf_balance' => 5000.00,
                'share_capital_balance' => 400000.00,
                'no_of_entitled_votes' => 60,
                'services_availed' => 'Fishing Equipment Loans, Training',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tech Innovators Coop',
                'contact_person' => 'Sophia Cruz',
                'type' => 'Technology',
                'address' => '789 Silicon Valley, Quezon City',
                'region' => 'NCR',
                'phone_number' => '09567890123',
                'email' => 'techinnovators@example.com',
                'tin' => '567-890-123',
                'coop_identification_no' => 'COOP-0005',
                'bod_chairperson' => 'Daniel Chua',
                'general_manager_ceo' => 'Victoria Lim',
                'ga_registration_status' => 'Registered',
                'total_asset' => 2000000.00,
                'total_income' => 900000.00,
                'cetf_remittance' => 100000.00,
                'cetf_required' => 110000.00,
                'cetf_balance' => 10000.00,
                'share_capital_balance' => 1200000.00,
                'no_of_entitled_votes' => 150,
                'services_availed' => 'Startup Funding, Mentorship Programs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
